In [4]:
import h5py 
import numpy as np
import pandas as pd

In [36]:
path_shear_catalog = '/global/projecta/projectdirs/lsst/groups/WL/users/zuntz/data/cosmoDC2-1.1.4_oneyear_unit_response/shear_catalog.hdf5' #needed for source selector, output of TXCosmoDC2Mock
path_photometry_catalog = '/global/projecta/projectdirs/lsst/groups/WL/users/zuntz/data/cosmoDC2-1.1.4_oneyear_unit_response/photometry_catalog.hdf5' # output of TXCosmoDC2Mock, needed for lens auxiliar maps
#path_lens_photometry_catalog = '/global/projecta/projectdirs/lsst/groups/WL/users/zuntz/data/cosmoDC2-1.1.4_oneyear_unit_response/photometry_catalog.hdf5' # its the same as in above
path_photoz_trained_model = '/global/projecta/projectdirs/lsst/groups/WL/users/zuntz/data/cosmoDC2-1.1.4_oneyear_unit_response/cosmoDC2_trees_i25.3.npy'
path_calibration_table = '/global/projecta/projectdirs/lsst/groups/WL/users/zuntz/data/cosmoDC2-1.1.4_oneyear_unit_response/sample_cosmodc2_w10year_errors.dat' #needed for source selector
path_redmagic_catalog = '/global/projecta/projectdirs/lsst/groups/WL/users/zuntz/data/redmagic/cosmoDC2_v1.1.4_run_redmagic_highdens.fit'

In [3]:
shear = h5py.File(path_shear_catalog,'r')

In [4]:
shear.keys()

<KeysViewHDF5 ['metacal', 'provenance', 'shear']>

In [5]:
shear['metacal'].keys()

<KeysViewHDF5 ['dec', 'id', 'mcal_T', 'mcal_T_1m', 'mcal_T_1p', 'mcal_T_2m', 'mcal_T_2p', 'mcal_T_err', 'mcal_T_err_1m', 'mcal_T_err_1p', 'mcal_T_err_2m', 'mcal_T_err_2p', 'mcal_flags', 'mcal_flags_1m', 'mcal_flags_1p', 'mcal_flags_2m', 'mcal_flags_2p', 'mcal_g1', 'mcal_g1_1m', 'mcal_g1_1p', 'mcal_g1_2m', 'mcal_g1_2p', 'mcal_g2', 'mcal_g2_1m', 'mcal_g2_1p', 'mcal_g2_2m', 'mcal_g2_2p', 'mcal_mag_err_i', 'mcal_mag_err_i_1m', 'mcal_mag_err_i_1p', 'mcal_mag_err_i_2m', 'mcal_mag_err_i_2p', 'mcal_mag_err_r', 'mcal_mag_err_r_1m', 'mcal_mag_err_r_1p', 'mcal_mag_err_r_2m', 'mcal_mag_err_r_2p', 'mcal_mag_err_z', 'mcal_mag_err_z_1m', 'mcal_mag_err_z_1p', 'mcal_mag_err_z_2m', 'mcal_mag_err_z_2p', 'mcal_mag_i', 'mcal_mag_i_1m', 'mcal_mag_i_1p', 'mcal_mag_i_2m', 'mcal_mag_i_2p', 'mcal_mag_r', 'mcal_mag_r_1m', 'mcal_mag_r_1p', 'mcal_mag_r_2m', 'mcal_mag_r_2p', 'mcal_mag_z', 'mcal_mag_z_1m', 'mcal_mag_z_1p', 'mcal_mag_z_2m', 'mcal_mag_z_2p', 'mcal_psf_T_mean', 'mcal_psf_g1', 'mcal_psf_g2', 'mcal_s2n',

In [8]:
shear['metacal/mcal_mag_err_z_2p'][0:10]

array([0.00110605, 0.0009216 , 0.00047376, 0.00248905, 0.00071098,
       0.00037512, 0.00043556, 0.00293025, 0.00015762, 0.00041904])

In [11]:
shear['shear'].keys()

<KeysViewHDF5 ['dec', 'id', 'mcal_T', 'mcal_T_1m', 'mcal_T_1p', 'mcal_T_2m', 'mcal_T_2p', 'mcal_T_err', 'mcal_T_err_1m', 'mcal_T_err_1p', 'mcal_T_err_2m', 'mcal_T_err_2p', 'mcal_flags', 'mcal_flags_1m', 'mcal_flags_1p', 'mcal_flags_2m', 'mcal_flags_2p', 'mcal_g1', 'mcal_g1_1m', 'mcal_g1_1p', 'mcal_g1_2m', 'mcal_g1_2p', 'mcal_g2', 'mcal_g2_1m', 'mcal_g2_1p', 'mcal_g2_2m', 'mcal_g2_2p', 'mcal_mag_err_i', 'mcal_mag_err_i_1m', 'mcal_mag_err_i_1p', 'mcal_mag_err_i_2m', 'mcal_mag_err_i_2p', 'mcal_mag_err_r', 'mcal_mag_err_r_1m', 'mcal_mag_err_r_1p', 'mcal_mag_err_r_2m', 'mcal_mag_err_r_2p', 'mcal_mag_err_z', 'mcal_mag_err_z_1m', 'mcal_mag_err_z_1p', 'mcal_mag_err_z_2m', 'mcal_mag_err_z_2p', 'mcal_mag_i', 'mcal_mag_i_1m', 'mcal_mag_i_1p', 'mcal_mag_i_2m', 'mcal_mag_i_2p', 'mcal_mag_r', 'mcal_mag_r_1m', 'mcal_mag_r_1p', 'mcal_mag_r_2m', 'mcal_mag_r_2p', 'mcal_mag_z', 'mcal_mag_z_1m', 'mcal_mag_z_1p', 'mcal_mag_z_2m', 'mcal_mag_z_2p', 'mcal_psf_T_mean', 'mcal_psf_g1', 'mcal_psf_g2', 'mcal_s2n',

In [9]:
photo = h5py.File(path_photometry_catalog,'r')

In [12]:
photo['photometry'].keys()

<KeysViewHDF5 ['dec', 'extendedness', 'g_mag', 'g_mag_err', 'i_mag', 'i_mag_err', 'id', 'mag_err_g', 'mag_err_i', 'mag_err_r', 'mag_err_u', 'mag_err_y', 'mag_err_z', 'mag_g', 'mag_i', 'mag_r', 'mag_u', 'mag_y', 'mag_z', 'r_mag', 'r_mag_err', 'ra', 'redshift_true', 'shear_1', 'shear_2', 'size_true', 'snr_g', 'snr_i', 'snr_r', 'snr_u', 'snr_y', 'snr_z', 'u_mag', 'u_mag_err', 'y_mag', 'y_mag_err', 'z_mag', 'z_mag_err']>

In [34]:
caltable = f = pd.read_csv(path_calibration_table)

In [35]:
caltable

#id sz ra dec u uerr g gerr r rerr i ierr z zerr y yerr galid Av
0       0 0.0220 62.584977 -40.334110  17.6159 0.0050 ...              
1       100 0.0489 62.737951 -40.310046  19.3351 0.005...              
2       200 0.0258 61.679292 -41.217925  23.0562 0.014...              
3       300 0.0292 62.836708 -40.058639  23.7464 0.025...              
4       400 0.0336 62.349167 -40.069310  23.1186 0.015...              
5       500 0.0325 61.570107 -40.943441  23.6385 0.022...              
6       600 0.0706 61.901785 -39.756100  19.2633 0.005...              
7       700 0.0634 61.389067 -39.275928  24.7660 0.061...              
8       800 0.0672 61.260704 -40.817689  25.3300 0.102...              
9       900 0.0522 62.217480 -40.393876  22.1550 0.008...              
10      1000 0.0587 61.769055 -39.095970  22.1930 0.00...              
11      1100 0.0684 61.853141 -40.445004  26.2448 0.23...              
12      1200 0.0613 61.891983 -40.901151  24.8306 0.06...              
13      1300 0.0549 60.884026 -40.237558  23.0042 0.01...              
14      1400 0.0623 62.717614 -40.828996  24.7060 0.05...              
15      1500 0.0578 62.191850 -39.628936  24.0322 0.03...              
16      1600 0.0611 61.578500 -40.255427  25.6569 0.13...              
17      1700 0.0623 62.161861 -40.493417  25.5600 0.12...              
18      1800 0.0794 62.334726 -41.106786  23.1512 0.01...              
19      1900 0.0903 61.549143 -40.195733  19.5091 0.00...              
20      2000 0.0763 62.418638 -39.844746  24.3296 0.04...              
21      2100 0.0920 61.776163 -39.699382  21.9577 0.00...              
22      2200 0.0772 62.375401 -40.934345  20.4769 0.00...              
23      2300 0.0995 61.867050 -40.071268  23.6508 0.02...              
24      2400 0.1001 62.365690 -41.193744  26.2293 0.23...              
25      2500 0.0775 62.556887 -39.813917  23.8582 0.02...              
26      2600 0.0858 62.490000 -40.784133  25.4960 0.11...              
27      2700 0.0972 62.114707 -40.132664  25.5915 0.13...              
28      2800 0.0965 61.653525 -39.062666  23.4189 0.01...              
29      2900 0.0828 62.438715 -40.805393  26.2164 0.23...              
...                                                   ...              
104074  10407400 2.5202 65.834908 -38.044652  25.4784 ...              
104075  10407500 2.5396 66.702121 -38.731638  24.8733 ...              
104076  10407600 2.5330 66.550366 -37.800771  24.7814 ...              
104077  10407700 2.5145 66.256477 -38.367487  26.8702 ...              
104078  10407800 2.4610 67.096805 -38.707444  28.1779 ...              
104079  10407900 2.5122 65.950124 -38.626926  25.4649 ...              
104080  10408000 2.6078 66.369127 -39.182582  25.5228 ...              
104081  10408100 2.6014 65.463870 -37.948711  24.8793 ...              
104082  10408200 2.5851 66.718502 -38.598549  24.8216 ...              
104083  10408300 2.6495 66.682568 -38.857849  25.4563 ...              
104084  10408400 2.6262 64.999665 -38.573688  26.3477 ...              
104085  10408500 2.6136 65.766604 -39.440811  25.6927 ...              
104086  10408600 2.5938 66.016736 -38.066004  23.9843 ...              
104087  10408700 2.7131 67.315952 -38.745485  25.9693 ...              
104088  10408800 2.7251 66.237816 -38.781262  26.5363 ...              
104089  10408900 2.7088 66.906982 -38.715204  24.7397 ...              
104090  10409000 2.6662 67.014047 -38.446636  24.7803 ...              
104091  10409100 2.6959 65.196200 -39.096484  23.3849 ...              
104092  10409200 2.7075 65.667964 -39.162422  25.6192 ...              
104093  10409300 2.7640 65.543633 -38.178764  26.4196 ...              
104094  10409400 2.7844 66.351051 -38.018459  25.3790 ...              
104095  10409500 2.7824 66.405631 -37.914837  25.5534 ...              
104096  10409600 2.7893 66.003104 -39.739997  26.5325 ...              
104097  10409700 2.8185 66.908028 -38.385662  2

## Check some TXPipe outputs

In [2]:
path_output = '../../TXPipe/data/cosmodc2/outputs_redmagic/2021/december14/7sbins/'

In [14]:
shear_tomo_cat = h5py.File(path_output+'shear_tomography_catalog.hdf5','r')

In [15]:
shear_tomo_cat.keys()

<KeysViewHDF5 ['provenance', 'response', 'tomography']>

In [16]:
shear_tomo_cat['tomography'].keys()

<KeysViewHDF5 ['N_eff', 'N_eff_2d', 'mean_e1', 'mean_e1_2d', 'mean_e2', 'mean_e2_2d', 'sigma_e', 'sigma_e_2d', 'source_bin', 'source_counts', 'source_counts_2d']>

In [19]:
shear_tomo_cat['tomography/mean_e1']

<HDF5 dataset "mean_e1": shape (7,), type "<f4">

In [20]:
shear_tomo_cat['tomography/source_bin']

<HDF5 dataset "source_bin": shape (209893233,), type "<i4">

In [23]:
shear_tomo_cat['tomography/sigma_e']

<HDF5 dataset "sigma_e": shape (7,), type "<f4">

In [24]:
shear_tomo_cat['tomography/source_counts']

<HDF5 dataset "source_counts": shape (7,), type "<i4">

In [26]:
shear_tomo_cat['response'].keys()

<KeysViewHDF5 ['R_S', 'R_S_2d', 'R_gamma', 'R_gamma_mean', 'R_gamma_mean_2d', 'R_total', 'R_total_2d']>

In [28]:
shear_tomo_cat['response/R_gamma']

<HDF5 dataset "R_gamma": shape (209893233, 2, 2), type "<f4">

### Lens cats

In [4]:
lens_cat = h5py.File(path_output+'lens_catalog.hdf5','r')

In [6]:
lens_cat.keys()

<KeysViewHDF5 ['lens', 'provenance']>

In [7]:
lens_cat['lens'].keys()

<KeysViewHDF5 ['chisq', 'dec', 'mag_err_g', 'mag_err_i', 'mag_err_r', 'mag_err_y', 'mag_err_z', 'mag_g', 'mag_i', 'mag_r', 'mag_y', 'mag_z', 'ra', 'zredmagic']>

In [10]:
lens_cat['provenance'].keys()

<KeysViewHDF5 []>

In [5]:
lens_tomo_cat = h5py.File(path_output+'lens_tomography_catalog.hdf5','r')

In [6]:
lens_tomo_cat.keys()

<KeysViewHDF5 ['provenance', 'tomography']>

In [7]:
lens_tomo_cat['tomography'].keys()

<KeysViewHDF5 ['lens_bin', 'lens_counts', 'lens_counts_2d', 'lens_weight']>

In [8]:
lens_tomo_cat['tomography/lens_bin'][:10]

array([2, 2, 2, 0, 3, 3, 3, 2, 2, 3], dtype=int32)

In [17]:
lens_tomo_cat['tomography/lens_counts'][:]

array([ 28779,  55406,  95005, 141527, 170392], dtype=int32)

In [18]:
lens_tomo_cat['tomography/lens_counts_2d'][:]

array([491109], dtype=int32)

In [10]:
len(lens_tomo_cat['tomography/lens_weight'][:])

577613

In [12]:
lens_z = h5py.File(path_output+'lens_photoz_stack.hdf5','r')

In [13]:
lens_z.keys()

<KeysViewHDF5 ['n_of_z', 'provenance']>

In [14]:
lens_z['n_of_z'].keys()

<KeysViewHDF5 ['lens']>

In [16]:
lens_z['n_of_z/lens'].keys()

<KeysViewHDF5 ['bin_0', 'bin_1', 'bin_2', 'bin_3', 'bin_4', 'z']>

In [20]:
lens_z['n_of_z/lens/bin_0'][:10]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
lens_z['n_of_z/lens/z'][:10]

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])