In [5]:
from astropy.io import fits
import h5py

In [8]:
folder = '/global/cscratch1/sd/jprat/gaussian_sims/seed1/'
shear = fits.open(folder + 'cat_shear_zbin1_signalnoise_S.fits')
pos = fits.open(folder + 'cat_count_zbin1_signalnoise_S.fits')

In [5]:
shear[1].data

FITS_rec([(4.1671684e-03, -41.791363,  0.07163807,  0.21858622, -0.00429532, -0.00240921,  0.07593339,  0.22099543, 30.077208),
          (5.5704545e-03, -41.78094 , -0.02079168, -0.01978052, -0.0010112 , -0.00342595, -0.01978048, -0.01635458, 36.13547 ),
          (3.5999933e+02, -41.77318 ,  0.18755609,  0.08119374,  0.0010779 , -0.00487303,  0.18647818,  0.08606676, 13.944377),
          ...,
          (3.1341232e+02, -40.02332 ,  0.13122234,  0.33484054,  0.00104142, -0.00280825,  0.13018091,  0.33764878, 37.858322),
          (3.1341272e+02, -40.02256 ,  0.07978594, -0.40736982,  0.00103886, -0.00279788,  0.07874707, -0.40457195, 42.09044 ),
          (3.1341528e+02, -40.02014 , -0.1662699 ,  0.16630867,  0.00099067, -0.00273839, -0.16726057,  0.16904706, 45.48615 )],
         dtype=(numpy.record, [('RA', '>f4'), ('DEC', '>f4'), ('E1', '>f4'), ('E2', '>f4'), ('G1', '>f4'), ('G2', '>f4'), ('rG1', '>f4'), ('rG2', '>f4'), ('W', '>f4')]))

In [6]:
w = shear[1].data['W']

In [7]:
w

array([30.077208, 36.13547 , 13.944377, ..., 37.858322, 42.09044 ,
       45.48615 ], dtype=float32)

In [9]:
pos[1].data

FITS_rec([( 8.7890625, -39.996506, 1.), (30.805664 , -39.996506, 1.),
          (45.81299  , -39.996506, 1.), ..., (59.728542 , -67.771996, 1.),
          (59.728542 , -67.771996, 1.), (59.775078 , -67.771996, 1.)],
         dtype=(numpy.record, [('RA', '>f4'), ('DEC', '>f4'), ('W', '>f4')]))

In [7]:
s2file = h5py.File('/global/cscratch1/sd/jprat/gaussian_sims/seed2/no_shape_noise/binned_shear_catalog.hdf5','r')
s3file = h5py.File('/global/cscratch1/sd/jprat/gaussian_sims/seed3/no_shape_noise/binned_shear_catalog.hdf5','r')

In [27]:
s2file['shear/bin_3/ra'][:10]

array([1.6125691e-03, 1.5516735e-02, 3.5997638e+02, 3.5998773e+02,
       3.5997690e+02, 3.5999567e+02, 3.5999017e+02, 6.4750493e-02,
       5.5640891e-02, 6.2064383e-02], dtype=float32)

In [26]:
s3file['shear/bin_3/ra'][:10]

array([1.6125691e-03, 1.5516735e-02, 3.5997638e+02, 3.5998773e+02,
       3.5997690e+02, 3.5999567e+02, 3.5999017e+02, 6.4750493e-02,
       5.5640891e-02, 6.2064383e-02], dtype=float32)