## Obtain SRD scale cuts for galaxy clustering and galaxy-galaxy lensing (given a kmax)

In [1]:
import numpy as np
from astropy.cosmology import FlatLambdaCDM

In [2]:
cosmo = FlatLambdaCDM(H0=71, Om0=2.647887e-01, Tcmb0=2.725000e+00)
z_mean_l = [0.3, 0.5, 0.7, 0.9, 1.1] 
print(cosmo.comoving_distance(np.array(z_mean_l)))
chi_of_zl = np.array(cosmo.comoving_distance(np.array(z_mean_l)))

[1186.71766394 1885.2381223  2511.417963   3070.96831163 3571.09175523] Mpc


In [3]:
kmax = 0.213 # Mpc, equivalent to 0.3h/Mpc from page 47 here https://arxiv.org/pdf/1809.01669.pdf 
lmax_zl = kmax*chi_of_zl-0.5 #based on Eq.(4) from https://arxiv.org/pdf/1809.01669.pdf
print(lmax_zl)

theta_min_zl = 180/lmax_zl*60
print(theta_min_zl, 'arcmin')

[252.27086242 401.05572005 534.43202612 653.61625038 760.14254387]
[42.81112728 26.92892648 20.20836977 16.52345699 14.20786152] arcmin
